name: canon
channels:
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - h5py
  - mpi4py
  - Pillow
  - numpy
  - scipy
  - pandas
  - scikit-image
  - scikit-learn
  - tensorflow
  - Keras
  - joblib
  - yaml
